[package]
name = "clarabel_algebra"
version = "0.1.0"
authors = ["Paul Goulart <paul.goulart@eng.ox.ac.uk>"]
edition = "2021"
license = "Apache-2.0"
description = "Algebra interface for Clarabel"
keywords = ["optimization", "math"]
categories = ["optimization"]

[dependencies]
num-traits = "0.2"
