[package]
name = "clarabel"
version = "0.1.2"
authors = ["Paul Goulart <paul.goulart@eng.ox.ac.uk>"]
edition = "2021"
license = "Apache-2.0"
description = "Clarabel Conic Interior Point Solver"
readme = "README.md"
keywords = ["optimization", "math"]
categories = ["optimization"]

[dependencies]
num-traits = "0.2"
derive_builder = "0.11"
amd = "0.2.1"

[[example]]
name = "qp"
path = "examples/example_qp.rs"

[[example]]
name = "socp"
path = "examples/example_socp.rs"

[[example]]
name = "box"
path = "examples/example_big_box.rs"


# ------------------------------
# Optional python interface 
# ------------------------------

[features]
# enables python interface build via pyo3
python = ["dep:pyo3"]

[dependencies.pyo3]
optional = true
version = "0.16.1"
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
# "abi3-py37" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.7
features = ["extension-module", "abi3-py37"]

