[package]
name = "clarabel"
version = "0.2.0"
authors = ["Paul Goulart <paul.goulart@eng.ox.ac.uk>"]
edition = "2021"
license = "Apache-2.0"
description = "Clarabel Conic Interior Point Solver for Rust / Python"
readme = "README.md"
repository = "https://github.com/oxfordcontrol/Clarabel.rs"
keywords = ["convex", "optimization", "QP", "LP", "SOCP"]
categories = ["mathematics"]

[dependencies]
num-traits = "0.2"
derive_builder = "0.11"
amd = "0.2.1"

[[example]]
name = "lp"
path = "examples/rust/example_lp.rs"

[[example]]
name = "qp"
path = "examples/rust/example_qp.rs"

[[example]]
name = "socp"
path = "examples/rust/example_socp.rs"

[[example]]
name = "box"
path = "examples/rust/example_box.rs"

# ------------------------------
# Optional python interface 
# ------------------------------

[features]
# enables python interface build via pyo3
python = ["dep:pyo3"]

[dependencies.pyo3]
optional = true
version = "0.16.1"
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
# "abi3-py37" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.7
features = ["extension-module", "abi3-py37"]

[lib]
name = "clarabel"
# "cdylib" is necessary to produce a shared library that Python can import.
# "lib" is necessary to allow the ./examples to build
crate-type = ["cdylib","lib"]

# ------------------------------
# enable latex in docs 
# credit: https://github.com/victe/rust-latex-doc-minimal-example
# ------------------------------

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./html/docs-header.html" ]