[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "clarabel"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
]

dependencies = [
    'cffi',
    'numpy', 
    'scipy'
]