[package]
name = "clarabel_julia"
version = "0.1.2"
edition = "2021"

[lib]
name = "clarabel_julia"
crate-type = ["cdylib"]

[dependencies]
clarabel_algebra   = {path = "../clarabel_algebra"}
clarabel_solver    = {path = "../clarabel_solver"}
libc = "0.2"
