[package]
name = "clarabel_julia"
version = "0.1.0"
edition = "2021"

[lib]
name = "clarabel_julia"
crate-type = ["cdylib"]

[dependencies]
clarabel_solver = {path = "../solver"}
clarabel_algebra = {path = "../algebra"}
libc = "0.2"

[profile.release]
debug = true
